name: Test auto inc version action
on: push

jobs:
  build:
    name: Auto inc version action
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
          
      - name: Switch to Current Branch
        run: git checkout ${{ env.BRANCH }}
              
      - name: Set up Python 3.10.2
        uses: actions/setup-python@v1
        with:
          python-version: 3.10.2
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
      
      - name: Run unit tests
        run: python -m pytest --import-mode=append .

      - name: Build and run action
        uses: ./
        id: versioning
        with:
          mode: dev
          suffix: 'pre'
          github_token: ${{ secrets.GITHUB_TOKEN }}
      
      # - uses: ./
      #   id: stable_release
      #   with:
      #     mode: stable
      #     suffix: 'pre'
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      
      
      - name: Version parameters
        shell: bash
        run: |
          echo "${{ steps.versioning.outputs.version }}"
